### ISSUE TITLE
setting trigger channels correctly

### ISSUE THREAD

**Issue by tomas-zijdemans-vipps** [slack-samples/deno-message-translator#12]
https://github.com/slack-samples/deno-message-translator/blob/57e90396a1190d96b9798132689799e37ae3467d/functions/internals/trigger_operations.ts#L52

Shouldn't this line rather be:

`channel_ids: channel_ids,` ?

**Comment by hello-ashleyintech** [comment]
Hi, @tomas-zijdemans-vipps! Thanks for submitting your question 🙇 

I totally understand where you're coming from with your question and where the confusion might be - the `channel_ids` property being passed into that object is using something called ["object literal shorthand" / "object property shorthand"](https://blog.kevinchisholm.com/javascript/object-literal-shorthand-syntax-basics/#:~:text=JavaScript%20Object%20Literal%20Shorthand%20Syntax%20is%20a%20feature%20that%20provides,easier%20to%20read%20and%20understand.), which is used in JS and TS to pass in values to an object key when the value variable shares the same name as the key value, such as is the case with `channel_ids`. It is a more simplified way to write the code you provided, `channel_ids: channel_ids`.

I couldn't find an in-depth TS explanation, but you can see a JS example for this [here](https://javascript.plainenglish.io/object-literals-using-object-property-shorthand-6360825c60ef). I hope this helps!
