### ISSUE TITLE
チャンネルを追加しようとすると「Slackになかなか接続できません」と表示される

### ISSUE THREAD

**Issue by dokokanokafka** [slack-samples/deno-message-translator#22]
添付の通り、SlackのConfigurator for DeepL Translatorのワークフローを使い、
チャンネルを追加しようとすると「Slackになかなか接続できません」と表示されます。

- アプリケーションはデプロイされている
- 既存のチャンネルの設定のままであれば、ワークフローでConfirmを押下しても成功する
- ` slack trigger create --trigger-def triggers/configurator.ts` で新しくリンク作成しても事象は変わらない
ことは確認しました。

数ヶ月前は同様の事象は確認されませんでしたが、日を跨いでも発生します。

こちらはやはり、Slack側の通信が原因となるでしょうか。

![スクリーンショット 2023-09-13 12 04 53](https://github.com/slack-samples/deno-message-translator/assets/61672244/002ec9d9-40fd-4ebd-bfcc-387d7531f8ff)

**Comment by seratch** [comment]
@dokokanokafka 手元では再現しませんでした。CLI の `slack activity` でログを確認してみてください。何か処理の途中でエラーになっているのかもしれません。このサンプルアプリのコードに修正が必要であれば、修正いたします。あるいは大量のチャンネルを登録していてタイムアウトしているなどの理由の場合は、ちょっと回避するのは難しいかもしれません。

**Comment by dokokanokafka** [comment]
@seratch 
ご返信いただきありがとうございます！

`Error: Failed to update a trigger! (response: {"ok":false,"error":"invalid_arguments","response_metadata":{"messages":["[ERROR] no more than 20 items allowed [json-pointer:/event/channel_ids]"]}})`

ログを確認してみたところ、上記のエラーが表示されていたため
登録チャンネル数の上限値に達したと思われます。
こちらはアプリ側で上限数を増やすことや、そうでない場合仕様変更が可能となるものなのでしょうか。
ご検討いただければ幸いです🙇‍♂️

**Comment by seratch** [comment]
@dokokanokafka 共有ありがとうございます。プラットフォーム側の仕様変更はちょっと難しいですが、20 チャンネルごとにトリガーを分ければ回避することは可能ですね。あるいは書かれているようにアプリを複数に分けてそれぞれに最大 20 まで設定するということも可能ではあります。

このサンプルアプリのリポジトリに関してはとりあえず 20 を超えた場合のエラーがわかりやすくなるようには改善してこのチケットを閉じたいと思います。もし @dokokanokafka さんの方でコードのカスタマイズが可能であればご利用のアプリについてはトリガーを複数作成するよう変更されれば、この制限はなくなります。ただし、カスタムステップは 15 秒以内に処理を終了する必要がありますので、その点はご留意ください。
