### ISSUE TITLE
The translation workflow invocation fails due to not_opted_into_overages error

### ISSUE THREAD

**Issue by dokokanokafka** [slack-samples/deno-message-translator#30]
@seratch 

- https://github.com/slack-samples/deno-message-translator/issues/22

以前質問させていただいた者です。
表記の通り、今月からDeepL翻訳のアプリケーションが動作しなくなっております。

slack acticityを実行すると、エラーログは以下のように表示されています(一部マスキングさせてもらいました)
```
2023-11-24 06:10:20 [error] [Wf05H2RN8952] (Trace=xxx) Trigger for workflow 'Maintain the trigger settings and bot user memberships' failed: not_opted_into_overages
2023-11-24 08:01:51 [error] [Wf05GTNHQC2J] (Trace=xxx) Trigger for workflow 'DeepL translation' failed: not_opted_into_overages
2023-11-24 09:27:30 [error] [Wf05GXEPDB29] (Trace=xxx) Trigger for workflow 'Configure DeepL translator app in channels' failed: not_opted_into_overages
```

調査したところ、翻訳のアプリケーションはプレミアムワークフローとなり
利用しているプランの上限実行数となる、1000回を超えてしまったことが原因と考えています。

11/1からの通算で、2日経たずで1000回を超えてしまったそうなのですが、
こちら翻訳アプリケーションを利用する際には実行回数の上限を変更する(つまり、プランの上限を超えたら従量課金として利用していく)以外に
技術的に実行数を抑制させる方法はありますでしょうか。

こちらデプロイしたコードは、.envを除いてはmainブランチのコードから特に変更はしていない状況です。
ご確認よろしくお願いいたします。

**Comment by dokokanokafka** [comment]
@seratch 
メンションさせていただきます。

**Comment by seratch** [comment]
@dokokanokafka ご質問ありがとうございます。

このエラーはご推察通り、翻訳ワークフローを有効にしたチャンネル群でのリアクションをつけるイベントが二日間で 1,000 件に達し、無料枠のワークフロー実行数を全て消費したという状況で発生しているものです。

>こちら翻訳アプリケーションを利用する際には実行回数の上限を変更する(つまり、プランの上限を超えたら従量課金として利用していく)以外に技術的に実行数を抑制させる方法はありますでしょうか。

特定のリアクションのみに反応するようカスタイズするのがよいかと思います。以下の記事で日本語で説明してますが、トリガーには filter を設定することができます。これによって特定のリアクション絵文字以外ではワークフローを実行しないよう制御することができます。
https://qiita.com/seratch/items/a4770243f3799b553e9c

具体的には記事中にあるように絵文字の名前を指定した filter.root.statement を追加します。例えば `:flag-jp:` にのみ反応させたい場合は、以下のような statement になります。
```javascript
    // 特定のリアクションのときだけワークフローを実行するよう条件を指定
    filter: {
      version: 1,
      root: { statement: "{{data.reaction}} == 'jp'" },
    },
```

OR 条件も指定できますので、詳しくは https://api.slack.com/automation/triggers/event#filters をご参照ください。:jp: と :us: であれば以下のようになります。

```javascript
    filter: {
      version: 1,
      root: {
        operator: "OR",
        inputs: [
          { statement: "{{data.reaction}} == 'jp'" },
          { statement: "{{data.reaction}} == 'us'" },
        ],
      },
    },
```

アプリに手を入れる箇所ですが、トリガーを作成・更新しているこちらのコードに filter を追加してください：
https://github.com/slack-samples/deno-message-translator/blob/1111a872e208027a4121b739eeaa76120983b9fa/functions/internals/trigger_operations.ts#L44-L81

その上で設定モーダルから保存し直すことで filter が有効になります。

もう少し検証をした上で、こちらのリポジトリのコードも最適なコストで利用いただけるようにしたいと考えていますが、その変更の時期はお約束できないため、とりあえずは上記のカスタマイズをご検討ください。

なお、この新しいプラットフォーム機能の無料枠は利用前の検証を行なっていただくことを目的に提供されており、基本的には利用料をお支払いいただく想定となっております。予算の関係等で難しい場合、Heroku などホスティング環境を別途ご用意いただく必要はありますが、アプリ利用には一切費用がかからない https://github.com/seratch/deepl-for-slack というサンプルアプリも公開しております。こちらであれば、従量課金ではない形で同等の機能を実現することができますので、ご興味あればご確認ください。

ご質問ありがとうございました。

**Comment by dokokanokafka** [comment]
@seratch 
ご返事いただき誠にありがとうございます。

現状のところ、リアクション全てに対してトリガーがかかるようになっていることは
存じてなかったので、参考になりました。

今月からの仕様変更に合わせた形で、アプリ側も対応していただくのを望むものの、
まずはご教示いただいたサンプルコードを元に、filterを有効にする形で
実行回数を減らすのを試みる方向で、対応させていただこうと思っております。

早急に回答いただきましてありがとうございます。

**Comment by seratch** [comment]
@dokokanokafka 改善案を実装しました。こちらの実装をぜひお試しください: https://github.com/slack-samples/deno-message-translator/pull/31

filter の statement は 18 個までしか持てず、絵文字としてはその半分の 9 個まで指定できる実装になっています。それ以上の絵文字を有効にされたい場合はお手数ですが、そちらでカスタマイズをお願いいたします。

**Comment by dokokanokafka** [comment]
@seratch 
拝見しましたが、絵文字は数絞る想定で考えておりましたので
9個までで十分だと思いました。
早速改善くださりありがとうございます！取り急ぎお礼させてください。
